# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-30 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adddoctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='docname',
            field=models.CharField(max_length=200, verbose_name='Doctor Name'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='email',
            field=models.CharField(max_length=200, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='hosname',
            field=models.CharField(max_length=400, verbose_name='Hospital Name'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='password',
            field=models.CharField(max_length=200, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='username',
            field=models.CharField(max_length=200, verbose_name='Username'),
        ),
    ]
