# Generated by Django 2.0 on 2018-10-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestOrgan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('bgroup', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('requestOrg', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='OrganRequest',
        ),
    ]
