# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-31 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRequestOrgan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctorname', models.CharField(max_length=200)),
                ('Hospitalname', models.CharField(max_length=200)),
                ('Patientname', models.CharField(max_length=200)),
                ('Patienttype', models.CharField(max_length=200)),
                ('Bloodgroup', models.CharField(max_length=200)),
                ('Organs', models.CharField(max_length=200)),
                ('Reason', models.CharField(max_length=300)),
                ('Description', models.CharField(max_length=500)),
                ('Contactnumber', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
            ],
        ),
    ]
