# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-01 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreq',
            name='Gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='organ',
            name='type_of_organ',
            field=models.CharField(choices=[('HEART', 'HEART'), ('LUNGS', 'LUNGS'), ('KIDNEY', 'KIDNEY'), ('LIVER', 'LIVER'), ('TISSUE', 'TISSUE'), ('PANCREAS', 'PANCREAS'), ('CORNEAS', 'CORNEAS'), ('EYES', 'EYES')], default='HEART', max_length=15, verbose_name='Organ'),
        ),
        migrations.AlterField(
            model_name='organreq',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10),
        ),
    ]
