# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-01 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181101_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreq',
            name='Donate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donate', to='app.Organ'),
        ),
    ]
