# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-01 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181101_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationreq',
            old_name='Firstname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='organreq',
            old_name='firstname',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='doctorrequestorgan',
            name='Bloodgroup',
        ),
        migrations.RemoveField(
            model_name='donationreq',
            name='Blood_group',
        ),
        migrations.RemoveField(
            model_name='donationreq',
            name='Lastname',
        ),
        migrations.RemoveField(
            model_name='organreq',
            name='lastname',
        ),
    ]
