# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-01 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181101_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organreq',
            name='bgroup',
        ),
    ]
