# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-02 04:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_organreq_bgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssingedOrgans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='app.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DonateOrgan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=500)),
                ('District', models.CharField(max_length=200)),
                ('Pincode', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('Relative_name', models.CharField(max_length=200)),
                ('Relationship', models.CharField(max_length=200)),
                ('Contact', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.RemoveField(
            model_name='donationreq',
            name='Donate',
        ),
        migrations.RemoveField(
            model_name='organreq',
            name='organ',
        ),
        migrations.AddField(
            model_name='organ',
            name='donor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DonationReq',
        ),
        migrations.DeleteModel(
            name='OrganReq',
        ),
        migrations.AddField(
            model_name='donateorgan',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organ', to='app.Organ'),
        ),
        migrations.AddField(
            model_name='assingedorgans',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_organ', to='app.Organ'),
        ),
    ]
