# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-02 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181102_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorrequestorgan',
            name='Doctor',
        ),
        migrations.AddField(
            model_name='doctorrequestorgan',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
