# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-02 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181102_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='B+', max_length=10, verbose_name='BGroup'),
        ),
    ]
