# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-02 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181102_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorrequestorgan',
            old_name='Organs',
            new_name='organs',
        ),
    ]
