# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-02 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181102_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdatsSummary',
            fields=[
            ],
            options={
                'verbose_name': 'ODATS Summary',
                'verbose_name_plural': 'ODATS Summary',
                'proxy': True,
                'indexes': [],
            },
            bases=('app.assingedorgans',),
        ),
        migrations.RenameField(
            model_name='doctorrequestorgan',
            old_name='doctor',
            new_name='Doctor',
        ),
    ]
