# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-02 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181103_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assingedorgans',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
