# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-04 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20181103_0036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odatssummary',
            options={'verbose_name': 'ODATS - Stats', 'verbose_name_plural': 'ODATS - Stats'},
        ),
        migrations.AlterField(
            model_name='organ',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datetime'),
        ),
    ]
