# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-14 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20181105_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorrequestorgan',
            name='req_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='datetime'),
            preserve_default=False,
        ),
    ]
