# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-13 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('bgroup', models.CharField(max_length=200)),
                ('hname', models.CharField(max_length=200)),
                ('items', models.CharField(max_length=200)),
            ],
        ),
    ]
