# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-19 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonationRequest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=500)),
                ('District', models.CharField(max_length=200)),
                ('Pincode', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('Blood_group', models.CharField(max_length=200)),
                ('Relative_name', models.CharField(max_length=200)),
                ('Relationship', models.CharField(max_length=200)),
                ('Contact', models.CharField(max_length=200)),
                ('Doante', models.CharField(max_length=200)),
                ('Spec_item1', models.CharField(max_length=200)),
                ('Spec_item2', models.CharField(max_length=200)),
                ('Spec_item3', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='DonationRequest',
        ),
    ]
