# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-30 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonationRequest', '0004_auto_20181030_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=500)),
                ('District', models.CharField(max_length=200)),
                ('Pincode', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('Blood_group', models.CharField(max_length=200)),
                ('Relative_name', models.CharField(max_length=200)),
                ('Relationship', models.CharField(max_length=200)),
                ('Contact', models.CharField(max_length=200)),
                ('Donate', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='DonationReques',
        ),
    ]
