# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-31 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationReques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=200, verbose_name='First Name')),
                ('Lastname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('Address', models.CharField(max_length=500)),
                ('District', models.CharField(max_length=200)),
                ('Pincode', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Gender', models.PositiveSmallIntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')], default=0, verbose_name='Gender')),
                ('Bloodgroup', models.CharField(max_length=200, verbose_name='Bloodgroup')),
                ('Relative_name', models.CharField(max_length=200)),
                ('Relationship', models.CharField(max_length=200)),
                ('Contact', models.CharField(max_length=200)),
                ('Donate', models.PositiveSmallIntegerField(choices=[(0, 'HEART'), (1, 'LUNGS'), (2, 'KIDNEY'), (3, 'LIVER'), (4, 'TISSUE'), (5, 'PANCREAS'), (6, 'CORNEAS'), (7, 'EYES')], default=0, verbose_name='Donate')),
            ],
            options={
                'verbose_name': 'DonationReques',
            },
        ),
    ]
