# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-13 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosname', models.CharField(max_length=200)),
                ('hosaddress', models.CharField(max_length=400)),
                ('licno', models.CharField(max_length=200)),
                ('certificate', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('nameofgm', models.CharField(max_length=200)),
                ('departments', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=300)),
            ],
        ),
    ]
